POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjViMWUyNmQyNWY1NWQ3MGExNmQzZjk2NSIsImlhdCI6MTUyODcwMjY3OH0.u-eTWTC2bOEXEJb3mR8JtjRtYWty2e7vPjvLlPIGqXA

{
    "title": "Type wars(test)",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
}

###
GET http://localhost:3003/api/blogs/5b1e27835f55d70a16d3f968

###
DELETE http://localhost:3003/api/blogs/5b1e27835f55d70a16d3f968
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjViMWUyNmQyNWY1NWQ3MGExNmQzZjk2NSIsImlhdCI6MTUyODcwMjY3OH0.u-eTWTC2bOEXEJb3mR8JtjRtYWty2e7vPjvLlPIGqXA

###
PUT http://localhost:3003/api/blogs/5b1a968b300cbd1d10ebf627
content-type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 0
}

###
GET http://localhost:3003/api/users


###
POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "mnajarian",
  "name": "Mahdi Najjarian",
  "password": "full"
}

###
POST http://localhost:3001/api/login
content-type: application/json

{
  "username": "mnajarian",
  "password": "full"
}

###
POST http://localhost:3001/api/users/
content-type: application/json

{
  "username": "mnajarian",
  "password": "full"
}